# Copyright 2025-2026 Nuvolaris Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

root = "."
tmp_dir = "tmp"

[build]
  cmd = "sed -i '' 's/^Build: .*/Build: dev_'$(date +%y.%j.%H%M)'/' version.txt && env GOOS=linux GOARCH=arm64 go build -o ./tmp/trustable . && kubectl -n nuvolaris cp -c trustable ./tmp/trustable trustable-0:/usr/local/bin/trustable && kubectl -n nuvolaris exec -c trustable trustable-0 -- supervisorctl restart trustable"
  bin = "/usr/bin/true"
  delay = 1000
  exclude_dir = ["tmp", "workspace", "workbench", "web", "node_modules", "image", "trureact", "truchat"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
