===============================================================================
TRUSTANT - THIRD-PARTY COMPONENTS
===============================================================================

Trustant (https://trustant.ai) is Copyright 2025-2026 Nuvolaris Inc and is
licensed under the GNU Affero General Public License v3 or later.

This file lists the third-party software Trustant includes, bundles into
its container image, downloads at run time or installs into the
development VM, with each component's license (SPDX expression).

- LICENSE holds the full text of every license named here.
- NOTICE holds the copyright and NOTICE statements of the components.

GENERATED by ./deps.sh from legal/deps.manual.txt, go.mod, the npm
lockfiles, acp/pi.version, acp/extensions/requirements.txt and
oplugins/prereq.yml. Do not edit by hand: edit those inputs and rerun.


1. GO BINARY (trustant)
=======================

Compiled into the single trustant executable.

NAME                             VERSION  LICENSE       HOMEPAGE
----                             -------  -------       --------
github.com/coder/websocket       1.8.15   ISC           https://github.com/coder/websocket
github.com/creack/pty            1.1.24   MIT           https://github.com/creack/pty
Go standard library and runtime  1.25.5   BSD-3-Clause  https://go.dev


2. FRONTEND ASSETS VENDORED IN web/
===================================

Embedded into the trustant executable and served to the browser.

NAME                                              VERSION  LICENSE  HOMEPAGE
----                                              -------  -------  --------
@tailwindcss/browser (web/tailwind.js)            4.1.18   MIT      https://github.com/tailwindlabs/tailwindcss
@xterm/addon-fit (web/js/xterm-addon-fit.min.js)  0.11.0   MIT      https://github.com/xtermjs/xterm.js
@xterm/xterm (web/js/xterm.min.js, xterm.css)     6.0.0    MIT      https://github.com/xtermjs/xterm.js
codejar (web/js/codejar.min.js)                   4.2.0    MIT      https://github.com/antonmedv/codejar
marked (web/js/marked.min.js)                     15.0.12  MIT      https://github.com/markedjs/marked


3. GIT SUBMODULES
=================

Source checked out in this repository and built into the image.

NAME                                 VERSION            LICENSE            HOMEPAGE
----                                 -------            -------            --------
acp (TruACP)                         main               AGPL-3.0-or-later  https://github.com/trustant/trustant-acp
mcp (openserverless-mcp)             main               Apache-2.0         https://github.com/trustant/openserverless-mcp
oplugins (openserverless-task)       0.9.0              Apache-2.0         https://github.com/trustable-ai/openserverless-task
oplugins-truinst                     main               AGPL-3.0-or-later  https://github.com/trustant/oplugins-truinst
packages (openserverless-packages)   main               Apache-2.0         https://github.com/trustant/openserverless-packages
pi-acp (fork, nested in acp/pi-acp)  0.0.31-trustant.1  MIT                https://github.com/trustable-ai/pi-acp
skills                               main               Apache-2.0         https://github.com/trustable-ai/skills


4. TRUACP (acp) - NPM PRODUCTION DEPENDENCIES
=============================================

Full production tree of acp/package-lock.json, bundled into truacp.cjs
and the TruACP web UI.

NAME                                               VERSION  LICENSE       HOMEPAGE
----                                               -------  -------       --------
@agentclientprotocol/sdk                           0.28.1   Apache-2.0    https://www.npmjs.com/package/@agentclientprotocol/sdk
@codemirror/state                                  6.5.0    MIT           https://www.npmjs.com/package/@codemirror/state
@codemirror/view                                   6.38.6   MIT           https://www.npmjs.com/package/@codemirror/view
@marijn/find-cluster-break                         1.0.2    MIT           https://www.npmjs.com/package/@marijn/find-cluster-break
@tanstack/react-virtual                            3.14.2   MIT           https://www.npmjs.com/package/@tanstack/react-virtual
@tanstack/virtual-core                             3.17.0   MIT           https://www.npmjs.com/package/@tanstack/virtual-core
@types/debug                                       4.1.13   MIT           https://www.npmjs.com/package/@types/debug
@types/estree                                      1.0.9    MIT           https://www.npmjs.com/package/@types/estree
@types/estree-jsx                                  1.0.5    MIT           https://www.npmjs.com/package/@types/estree-jsx
@types/hast                                        3.0.4    MIT           https://www.npmjs.com/package/@types/hast
@types/mdast                                       4.0.4    MIT           https://www.npmjs.com/package/@types/mdast
@types/ms                                          2.1.0    MIT           https://www.npmjs.com/package/@types/ms
@types/unist                                       2.0.11   MIT           https://www.npmjs.com/package/@types/unist
@types/unist                                       3.0.3    MIT           https://www.npmjs.com/package/@types/unist
@ungap/structured-clone                            1.3.1    ISC           https://www.npmjs.com/package/@ungap/structured-clone
bail                                               2.0.2    MIT           https://www.npmjs.com/package/bail
ccount                                             2.0.1    MIT           https://www.npmjs.com/package/ccount
character-entities                                 2.0.2    MIT           https://www.npmjs.com/package/character-entities
character-entities-html4                           2.1.0    MIT           https://www.npmjs.com/package/character-entities-html4
character-entities-legacy                          3.0.0    MIT           https://www.npmjs.com/package/character-entities-legacy
character-reference-invalid                        2.0.1    MIT           https://www.npmjs.com/package/character-reference-invalid
comma-separated-tokens                             2.0.3    MIT           https://www.npmjs.com/package/comma-separated-tokens
crelt                                              1.0.6    MIT           https://www.npmjs.com/package/crelt
debug                                              4.4.3    MIT           https://www.npmjs.com/package/debug
decode-named-character-reference                   1.3.0    MIT           https://www.npmjs.com/package/decode-named-character-reference
dequal                                             2.0.3    MIT           https://www.npmjs.com/package/dequal
devlop                                             1.1.0    MIT           https://www.npmjs.com/package/devlop
diff                                               8.0.4    BSD-3-Clause  https://www.npmjs.com/package/diff
escape-string-regexp                               5.0.0    MIT           https://www.npmjs.com/package/escape-string-regexp
estree-util-is-identifier-name                     3.0.0    MIT           https://www.npmjs.com/package/estree-util-is-identifier-name
extend                                             3.0.2    MIT           https://www.npmjs.com/package/extend
hast-util-to-jsx-runtime                           2.3.6    MIT           https://www.npmjs.com/package/hast-util-to-jsx-runtime
hast-util-whitespace                               3.0.0    MIT           https://www.npmjs.com/package/hast-util-whitespace
html-url-attributes                                3.0.1    MIT           https://www.npmjs.com/package/html-url-attributes
inline-style-parser                                0.2.7    MIT           https://www.npmjs.com/package/inline-style-parser
is-alphabetical                                    2.0.1    MIT           https://www.npmjs.com/package/is-alphabetical
is-alphanumerical                                  2.0.1    MIT           https://www.npmjs.com/package/is-alphanumerical
is-decimal                                         2.0.1    MIT           https://www.npmjs.com/package/is-decimal
is-hexadecimal                                     2.0.1    MIT           https://www.npmjs.com/package/is-hexadecimal
is-plain-obj                                       4.1.0    MIT           https://www.npmjs.com/package/is-plain-obj
js-tokens                                          4.0.0    MIT           https://www.npmjs.com/package/js-tokens
longest-streak                                     3.1.0    MIT           https://www.npmjs.com/package/longest-streak
loose-envify                                       1.4.0    MIT           https://www.npmjs.com/package/loose-envify
markdown-table                                     3.0.4    MIT           https://www.npmjs.com/package/markdown-table
mdast-util-find-and-replace                        3.0.2    MIT           https://www.npmjs.com/package/mdast-util-find-and-replace
mdast-util-from-markdown                           2.0.3    MIT           https://www.npmjs.com/package/mdast-util-from-markdown
mdast-util-gfm                                     3.1.0    MIT           https://www.npmjs.com/package/mdast-util-gfm
mdast-util-gfm-autolink-literal                    2.0.1    MIT           https://www.npmjs.com/package/mdast-util-gfm-autolink-literal
mdast-util-gfm-footnote                            2.1.0    MIT           https://www.npmjs.com/package/mdast-util-gfm-footnote
mdast-util-gfm-strikethrough                       2.0.0    MIT           https://www.npmjs.com/package/mdast-util-gfm-strikethrough
mdast-util-gfm-table                               2.0.0    MIT           https://www.npmjs.com/package/mdast-util-gfm-table
mdast-util-gfm-task-list-item                      2.0.0    MIT           https://www.npmjs.com/package/mdast-util-gfm-task-list-item
mdast-util-mdx-expression                          2.0.1    MIT           https://www.npmjs.com/package/mdast-util-mdx-expression
mdast-util-mdx-jsx                                 3.2.0    MIT           https://www.npmjs.com/package/mdast-util-mdx-jsx
mdast-util-mdxjs-esm                               2.0.1    MIT           https://www.npmjs.com/package/mdast-util-mdxjs-esm
mdast-util-phrasing                                4.1.0    MIT           https://www.npmjs.com/package/mdast-util-phrasing
mdast-util-to-hast                                 13.2.1   MIT           https://www.npmjs.com/package/mdast-util-to-hast
mdast-util-to-markdown                             2.1.2    MIT           https://www.npmjs.com/package/mdast-util-to-markdown
mdast-util-to-string                               4.0.0    MIT           https://www.npmjs.com/package/mdast-util-to-string
micromark                                          4.0.2    MIT           https://www.npmjs.com/package/micromark
micromark-core-commonmark                          2.0.3    MIT           https://www.npmjs.com/package/micromark-core-commonmark
micromark-extension-gfm                            3.0.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm
micromark-extension-gfm-autolink-literal           2.1.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm-autolink-literal
micromark-extension-gfm-footnote                   2.1.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm-footnote
micromark-extension-gfm-strikethrough              2.1.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm-strikethrough
micromark-extension-gfm-table                      2.1.1    MIT           https://www.npmjs.com/package/micromark-extension-gfm-table
micromark-extension-gfm-tagfilter                  2.0.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm-tagfilter
micromark-extension-gfm-task-list-item             2.1.0    MIT           https://www.npmjs.com/package/micromark-extension-gfm-task-list-item
micromark-factory-destination                      2.0.1    MIT           https://www.npmjs.com/package/micromark-factory-destination
micromark-factory-label                            2.0.1    MIT           https://www.npmjs.com/package/micromark-factory-label
micromark-factory-space                            2.0.1    MIT           https://www.npmjs.com/package/micromark-factory-space
micromark-factory-title                            2.0.1    MIT           https://www.npmjs.com/package/micromark-factory-title
micromark-factory-whitespace                       2.0.1    MIT           https://www.npmjs.com/package/micromark-factory-whitespace
micromark-util-character                           2.1.1    MIT           https://www.npmjs.com/package/micromark-util-character
micromark-util-chunked                             2.0.1    MIT           https://www.npmjs.com/package/micromark-util-chunked
micromark-util-classify-character                  2.0.1    MIT           https://www.npmjs.com/package/micromark-util-classify-character
micromark-util-combine-extensions                  2.0.1    MIT           https://www.npmjs.com/package/micromark-util-combine-extensions
micromark-util-decode-numeric-character-reference  2.0.2    MIT           https://www.npmjs.com/package/micromark-util-decode-numeric-character-reference
micromark-util-decode-string                       2.0.1    MIT           https://www.npmjs.com/package/micromark-util-decode-string
micromark-util-encode                              2.0.1    MIT           https://www.npmjs.com/package/micromark-util-encode
micromark-util-html-tag-name                       2.0.1    MIT           https://www.npmjs.com/package/micromark-util-html-tag-name
micromark-util-normalize-identifier                2.0.1    MIT           https://www.npmjs.com/package/micromark-util-normalize-identifier
micromark-util-resolve-all                         2.0.1    MIT           https://www.npmjs.com/package/micromark-util-resolve-all
micromark-util-sanitize-uri                        2.0.1    MIT           https://www.npmjs.com/package/micromark-util-sanitize-uri
micromark-util-subtokenize                         2.1.0    MIT           https://www.npmjs.com/package/micromark-util-subtokenize
micromark-util-symbol                              2.0.1    MIT           https://www.npmjs.com/package/micromark-util-symbol
micromark-util-types                               2.0.2    MIT           https://www.npmjs.com/package/micromark-util-types
ms                                                 2.1.3    MIT           https://www.npmjs.com/package/ms
parse-entities                                     4.0.2    MIT           https://www.npmjs.com/package/parse-entities
property-information                               7.2.0    MIT           https://www.npmjs.com/package/property-information
react                                              18.3.1   MIT           https://www.npmjs.com/package/react
react-dom                                          18.3.1   MIT           https://www.npmjs.com/package/react-dom
react-markdown                                     10.1.0   MIT           https://www.npmjs.com/package/react-markdown
remark-gfm                                         4.0.1    MIT           https://www.npmjs.com/package/remark-gfm
remark-parse                                       11.0.0   MIT           https://www.npmjs.com/package/remark-parse
remark-rehype                                      11.1.2   MIT           https://www.npmjs.com/package/remark-rehype
remark-stringify                                   11.0.0   MIT           https://www.npmjs.com/package/remark-stringify
scheduler                                          0.23.2   MIT           https://www.npmjs.com/package/scheduler
semver                                             7.8.2    ISC           https://www.npmjs.com/package/semver
space-separated-tokens                             2.0.2    MIT           https://www.npmjs.com/package/space-separated-tokens
stringify-entities                                 4.0.4    MIT           https://www.npmjs.com/package/stringify-entities
style-mod                                          4.1.3    MIT           https://www.npmjs.com/package/style-mod
style-to-js                                        1.1.21   MIT           https://www.npmjs.com/package/style-to-js
style-to-object                                    1.0.14   MIT           https://www.npmjs.com/package/style-to-object
trim-lines                                         3.0.1    MIT           https://www.npmjs.com/package/trim-lines
trough                                             2.2.0    MIT           https://www.npmjs.com/package/trough
unified                                            11.0.5   MIT           https://www.npmjs.com/package/unified
unist-util-is                                      6.0.1    MIT           https://www.npmjs.com/package/unist-util-is
unist-util-position                                5.0.0    MIT           https://www.npmjs.com/package/unist-util-position
unist-util-stringify-position                      4.0.0    MIT           https://www.npmjs.com/package/unist-util-stringify-position
unist-util-visit                                   5.1.0    MIT           https://www.npmjs.com/package/unist-util-visit
unist-util-visit-parents                           6.0.2    MIT           https://www.npmjs.com/package/unist-util-visit-parents
vfile                                              6.0.3    MIT           https://www.npmjs.com/package/vfile
vfile-message                                      4.0.3    MIT           https://www.npmjs.com/package/vfile-message
w3c-keyname                                        2.2.8    MIT           https://www.npmjs.com/package/w3c-keyname
ws                                                 8.21.1   MIT           https://www.npmjs.com/package/ws
zod                                                4.4.3    MIT           https://www.npmjs.com/package/zod
zwitch                                             2.0.4    MIT           https://www.npmjs.com/package/zwitch


5. PI-ACP (acp/pi-acp) - NPM PRODUCTION DEPENDENCIES
====================================================

Full production tree of acp/pi-acp/package-lock.json.

NAME                      VERSION  LICENSE     HOMEPAGE
----                      -------  -------     --------
@agentclientprotocol/sdk  0.26.0   Apache-2.0  https://www.npmjs.com/package/@agentclientprotocol/sdk
zod                       3.25.76  MIT         https://www.npmjs.com/package/zod


6. OPENSERVERLESS-MCP (mcp) - NPM PRODUCTION DEPENDENCIES
=========================================================

Full production tree of mcp/package-lock.json, installed globally in the
image.

NAME                       VERSION  LICENSE       HOMEPAGE
----                       -------  -------       --------
@hono/node-server          1.19.17  MIT           https://www.npmjs.com/package/@hono/node-server
@modelcontextprotocol/sdk  1.29.0   MIT           https://www.npmjs.com/package/@modelcontextprotocol/sdk
accepts                    2.0.0    MIT           https://www.npmjs.com/package/accepts
ajv                        8.20.0   MIT           https://www.npmjs.com/package/ajv
ajv-formats                3.0.1    MIT           https://www.npmjs.com/package/ajv-formats
body-parser                2.3.0    MIT           https://www.npmjs.com/package/body-parser
bytes                      3.1.2    MIT           https://www.npmjs.com/package/bytes
call-bind-apply-helpers    1.0.2    MIT           https://www.npmjs.com/package/call-bind-apply-helpers
call-bound                 1.0.4    MIT           https://www.npmjs.com/package/call-bound
content-disposition        1.1.0    MIT           https://www.npmjs.com/package/content-disposition
content-type               1.0.5    MIT           https://www.npmjs.com/package/content-type
content-type               2.0.0    MIT           https://www.npmjs.com/package/content-type
cookie                     0.7.2    MIT           https://www.npmjs.com/package/cookie
cookie-signature           1.2.2    MIT           https://www.npmjs.com/package/cookie-signature
cors                       2.8.6    MIT           https://www.npmjs.com/package/cors
cross-spawn                7.0.6    MIT           https://www.npmjs.com/package/cross-spawn
debug                      4.4.3    MIT           https://www.npmjs.com/package/debug
depd                       2.0.0    MIT           https://www.npmjs.com/package/depd
dunder-proto               1.0.1    MIT           https://www.npmjs.com/package/dunder-proto
ee-first                   1.1.1    MIT           https://www.npmjs.com/package/ee-first
encodeurl                  2.0.0    MIT           https://www.npmjs.com/package/encodeurl
es-define-property         1.0.1    MIT           https://www.npmjs.com/package/es-define-property
es-errors                  1.3.0    MIT           https://www.npmjs.com/package/es-errors
es-object-atoms            1.1.2    MIT           https://www.npmjs.com/package/es-object-atoms
escape-html                1.0.3    MIT           https://www.npmjs.com/package/escape-html
etag                       1.8.1    MIT           https://www.npmjs.com/package/etag
eventsource                3.0.7    MIT           https://www.npmjs.com/package/eventsource
eventsource-parser         3.1.0    MIT           https://www.npmjs.com/package/eventsource-parser
express                    5.2.1    MIT           https://www.npmjs.com/package/express
express-rate-limit         8.5.2    MIT           https://www.npmjs.com/package/express-rate-limit
fast-deep-equal            3.1.3    MIT           https://www.npmjs.com/package/fast-deep-equal
fast-uri                   3.1.5    BSD-3-Clause  https://www.npmjs.com/package/fast-uri
finalhandler               2.1.1    MIT           https://www.npmjs.com/package/finalhandler
forwarded                  0.2.0    MIT           https://www.npmjs.com/package/forwarded
fresh                      2.0.0    MIT           https://www.npmjs.com/package/fresh
function-bind              1.1.2    MIT           https://www.npmjs.com/package/function-bind
get-intrinsic              1.3.0    MIT           https://www.npmjs.com/package/get-intrinsic
get-proto                  1.0.1    MIT           https://www.npmjs.com/package/get-proto
gopd                       1.2.0    MIT           https://www.npmjs.com/package/gopd
has-symbols                1.1.0    MIT           https://www.npmjs.com/package/has-symbols
hasown                     2.0.4    MIT           https://www.npmjs.com/package/hasown
hono                       4.13.1   MIT           https://www.npmjs.com/package/hono
http-errors                2.0.1    MIT           https://www.npmjs.com/package/http-errors
iconv-lite                 0.7.2    MIT           https://www.npmjs.com/package/iconv-lite
inherits                   2.0.4    ISC           https://www.npmjs.com/package/inherits
ip-address                 10.4.0   MIT           https://www.npmjs.com/package/ip-address
ipaddr.js                  1.9.1    MIT           https://www.npmjs.com/package/ipaddr.js
is-promise                 4.0.0    MIT           https://www.npmjs.com/package/is-promise
isexe                      2.0.0    ISC           https://www.npmjs.com/package/isexe
jose                       6.2.3    MIT           https://www.npmjs.com/package/jose
json-schema-traverse       1.0.0    MIT           https://www.npmjs.com/package/json-schema-traverse
json-schema-typed          8.0.2    BSD-2-Clause  https://www.npmjs.com/package/json-schema-typed
math-intrinsics            1.1.0    MIT           https://www.npmjs.com/package/math-intrinsics
media-typer                1.1.0    MIT           https://www.npmjs.com/package/media-typer
merge-descriptors          2.0.0    MIT           https://www.npmjs.com/package/merge-descriptors
mime-db                    1.54.0   MIT           https://www.npmjs.com/package/mime-db
mime-types                 3.0.2    MIT           https://www.npmjs.com/package/mime-types
ms                         2.1.3    MIT           https://www.npmjs.com/package/ms
negotiator                 1.0.0    MIT           https://www.npmjs.com/package/negotiator
object-assign              4.1.1    MIT           https://www.npmjs.com/package/object-assign
object-inspect             1.13.4   MIT           https://www.npmjs.com/package/object-inspect
on-finished                2.4.1    MIT           https://www.npmjs.com/package/on-finished
once                       1.4.0    ISC           https://www.npmjs.com/package/once
parseurl                   1.3.3    MIT           https://www.npmjs.com/package/parseurl
path-key                   3.1.1    MIT           https://www.npmjs.com/package/path-key
path-to-regexp             8.4.2    MIT           https://www.npmjs.com/package/path-to-regexp
pkce-challenge             5.0.1    MIT           https://www.npmjs.com/package/pkce-challenge
proxy-addr                 2.0.7    MIT           https://www.npmjs.com/package/proxy-addr
qs                         6.15.2   BSD-3-Clause  https://www.npmjs.com/package/qs
range-parser               1.2.1    MIT           https://www.npmjs.com/package/range-parser
raw-body                   3.0.2    MIT           https://www.npmjs.com/package/raw-body
require-from-string        2.0.2    MIT           https://www.npmjs.com/package/require-from-string
router                     2.2.0    MIT           https://www.npmjs.com/package/router
safer-buffer               2.1.2    MIT           https://www.npmjs.com/package/safer-buffer
send                       1.2.1    MIT           https://www.npmjs.com/package/send
serve-static               2.2.1    MIT           https://www.npmjs.com/package/serve-static
setprototypeof             1.2.0    ISC           https://www.npmjs.com/package/setprototypeof
shebang-command            2.0.0    MIT           https://www.npmjs.com/package/shebang-command
shebang-regex              3.0.0    MIT           https://www.npmjs.com/package/shebang-regex
side-channel               1.1.1    MIT           https://www.npmjs.com/package/side-channel
side-channel-list          1.0.1    MIT           https://www.npmjs.com/package/side-channel-list
side-channel-map           1.0.1    MIT           https://www.npmjs.com/package/side-channel-map
side-channel-weakmap       1.0.2    MIT           https://www.npmjs.com/package/side-channel-weakmap
statuses                   2.0.2    MIT           https://www.npmjs.com/package/statuses
toidentifier               1.0.1    MIT           https://www.npmjs.com/package/toidentifier
type-is                    2.1.0    MIT           https://www.npmjs.com/package/type-is
unpipe                     1.0.0    MIT           https://www.npmjs.com/package/unpipe
vary                       1.1.2    MIT           https://www.npmjs.com/package/vary
which                      2.0.2    ISC           https://www.npmjs.com/package/which
wrappy                     1.0.2    ISC           https://www.npmjs.com/package/wrappy
zod                        3.25.76  MIT           https://www.npmjs.com/package/zod
zod-to-json-schema         3.25.2   ISC           https://www.npmjs.com/package/zod-to-json-schema


7. TRUSTANT-REACT-MCP (react-mcp) - NPM PRODUCTION DEPENDENCIES
===============================================================

Full production tree of react-mcp/package-lock.json, installed globally
in the image.

NAME                       VERSION  LICENSE       HOMEPAGE
----                       -------  -------       --------
@hono/node-server          1.19.15  MIT           https://www.npmjs.com/package/@hono/node-server
@modelcontextprotocol/sdk  1.29.0   MIT           https://www.npmjs.com/package/@modelcontextprotocol/sdk
accepts                    2.0.0    MIT           https://www.npmjs.com/package/accepts
ajv                        8.20.0   MIT           https://www.npmjs.com/package/ajv
ajv-formats                3.0.1    MIT           https://www.npmjs.com/package/ajv-formats
body-parser                2.3.0    MIT           https://www.npmjs.com/package/body-parser
bytes                      3.1.2    MIT           https://www.npmjs.com/package/bytes
call-bind-apply-helpers    1.0.2    MIT           https://www.npmjs.com/package/call-bind-apply-helpers
call-bound                 1.0.4    MIT           https://www.npmjs.com/package/call-bound
content-disposition        1.1.0    MIT           https://www.npmjs.com/package/content-disposition
content-type               1.0.5    MIT           https://www.npmjs.com/package/content-type
content-type               2.0.0    MIT           https://www.npmjs.com/package/content-type
cookie                     0.7.2    MIT           https://www.npmjs.com/package/cookie
cookie-signature           1.2.2    MIT           https://www.npmjs.com/package/cookie-signature
cors                       2.8.6    MIT           https://www.npmjs.com/package/cors
cross-spawn                7.0.6    MIT           https://www.npmjs.com/package/cross-spawn
debug                      4.4.3    MIT           https://www.npmjs.com/package/debug
depd                       2.0.0    MIT           https://www.npmjs.com/package/depd
dunder-proto               1.0.1    MIT           https://www.npmjs.com/package/dunder-proto
ee-first                   1.1.1    MIT           https://www.npmjs.com/package/ee-first
encodeurl                  2.0.0    MIT           https://www.npmjs.com/package/encodeurl
es-define-property         1.0.1    MIT           https://www.npmjs.com/package/es-define-property
es-errors                  1.3.0    MIT           https://www.npmjs.com/package/es-errors
es-object-atoms            1.1.2    MIT           https://www.npmjs.com/package/es-object-atoms
escape-html                1.0.3    MIT           https://www.npmjs.com/package/escape-html
etag                       1.8.1    MIT           https://www.npmjs.com/package/etag
eventsource                3.0.7    MIT           https://www.npmjs.com/package/eventsource
eventsource-parser         3.1.0    MIT           https://www.npmjs.com/package/eventsource-parser
express                    5.2.1    MIT           https://www.npmjs.com/package/express
express-rate-limit         8.6.0    MIT           https://www.npmjs.com/package/express-rate-limit
fast-deep-equal            3.1.3    MIT           https://www.npmjs.com/package/fast-deep-equal
fast-uri                   3.1.4    BSD-3-Clause  https://www.npmjs.com/package/fast-uri
finalhandler               2.1.1    MIT           https://www.npmjs.com/package/finalhandler
forwarded                  0.2.0    MIT           https://www.npmjs.com/package/forwarded
fresh                      2.0.0    MIT           https://www.npmjs.com/package/fresh
function-bind              1.1.2    MIT           https://www.npmjs.com/package/function-bind
get-intrinsic              1.3.0    MIT           https://www.npmjs.com/package/get-intrinsic
get-proto                  1.0.1    MIT           https://www.npmjs.com/package/get-proto
gopd                       1.2.0    MIT           https://www.npmjs.com/package/gopd
has-symbols                1.1.0    MIT           https://www.npmjs.com/package/has-symbols
hasown                     2.0.4    MIT           https://www.npmjs.com/package/hasown
hono                       4.12.32  MIT           https://www.npmjs.com/package/hono
http-errors                2.0.1    MIT           https://www.npmjs.com/package/http-errors
iconv-lite                 0.7.3    MIT           https://www.npmjs.com/package/iconv-lite
inherits                   2.0.4    ISC           https://www.npmjs.com/package/inherits
ip-address                 10.2.0   MIT           https://www.npmjs.com/package/ip-address
ipaddr.js                  1.9.1    MIT           https://www.npmjs.com/package/ipaddr.js
is-promise                 4.0.0    MIT           https://www.npmjs.com/package/is-promise
isexe                      2.0.0    ISC           https://www.npmjs.com/package/isexe
jose                       6.2.4    MIT           https://www.npmjs.com/package/jose
json-schema-traverse       1.0.0    MIT           https://www.npmjs.com/package/json-schema-traverse
json-schema-typed          8.0.2    BSD-2-Clause  https://www.npmjs.com/package/json-schema-typed
math-intrinsics            1.1.0    MIT           https://www.npmjs.com/package/math-intrinsics
media-typer                1.1.1    MIT           https://www.npmjs.com/package/media-typer
merge-descriptors          2.0.0    MIT           https://www.npmjs.com/package/merge-descriptors
mime-db                    1.54.0   MIT           https://www.npmjs.com/package/mime-db
mime-types                 3.0.2    MIT           https://www.npmjs.com/package/mime-types
ms                         2.1.3    MIT           https://www.npmjs.com/package/ms
negotiator                 1.0.0    MIT           https://www.npmjs.com/package/negotiator
object-assign              4.1.1    MIT           https://www.npmjs.com/package/object-assign
object-inspect             1.13.4   MIT           https://www.npmjs.com/package/object-inspect
on-finished                2.4.1    MIT           https://www.npmjs.com/package/on-finished
once                       1.4.0    ISC           https://www.npmjs.com/package/once
parseurl                   1.3.3    MIT           https://www.npmjs.com/package/parseurl
path-key                   3.1.1    MIT           https://www.npmjs.com/package/path-key
path-to-regexp             8.4.2    MIT           https://www.npmjs.com/package/path-to-regexp
pkce-challenge             5.0.1    MIT           https://www.npmjs.com/package/pkce-challenge
proxy-addr                 2.0.7    MIT           https://www.npmjs.com/package/proxy-addr
qs                         6.15.3   BSD-3-Clause  https://www.npmjs.com/package/qs
range-parser               1.3.0    MIT           https://www.npmjs.com/package/range-parser
raw-body                   3.0.2    MIT           https://www.npmjs.com/package/raw-body
require-from-string        2.0.2    MIT           https://www.npmjs.com/package/require-from-string
router                     2.2.0    MIT           https://www.npmjs.com/package/router
safer-buffer               2.1.2    MIT           https://www.npmjs.com/package/safer-buffer
send                       1.2.1    MIT           https://www.npmjs.com/package/send
serve-static               2.2.1    MIT           https://www.npmjs.com/package/serve-static
setprototypeof             1.2.0    ISC           https://www.npmjs.com/package/setprototypeof
shebang-command            2.0.0    MIT           https://www.npmjs.com/package/shebang-command
shebang-regex              3.0.0    MIT           https://www.npmjs.com/package/shebang-regex
side-channel               1.1.1    MIT           https://www.npmjs.com/package/side-channel
side-channel-list          1.0.1    MIT           https://www.npmjs.com/package/side-channel-list
side-channel-map           1.0.1    MIT           https://www.npmjs.com/package/side-channel-map
side-channel-weakmap       1.0.2    MIT           https://www.npmjs.com/package/side-channel-weakmap
statuses                   2.0.2    MIT           https://www.npmjs.com/package/statuses
toidentifier               1.0.1    MIT           https://www.npmjs.com/package/toidentifier
type-is                    2.1.0    MIT           https://www.npmjs.com/package/type-is
typescript                 5.9.3    Apache-2.0    https://www.npmjs.com/package/typescript
unpipe                     1.0.0    MIT           https://www.npmjs.com/package/unpipe
vary                       1.1.2    MIT           https://www.npmjs.com/package/vary
which                      2.0.2    ISC           https://www.npmjs.com/package/which
wrappy                     1.0.2    ISC           https://www.npmjs.com/package/wrappy
zod                        3.25.76  MIT           https://www.npmjs.com/package/zod
zod-to-json-schema         3.25.2   ISC           https://www.npmjs.com/package/zod-to-json-schema


8. CONTAINER IMAGE - UBUNTU 24.04 PACKAGES
==========================================

Installed with apt in image/Dockerfile. Each package's full copyright and
license statement ships in the image at /usr/share/doc/<package>/copyright.

NAME                        VERSION  LICENSE                                  HOMEPAGE
----                        -------  -------                                  --------
ca-certificates             distro   MPL-2.0                                  https://salsa.debian.org/debian/ca-certificates
curl                        distro   curl                                     https://curl.se
git                         distro   GPL-2.0-only                             https://git-scm.com
inetutils-telnet            distro   GPL-3.0-or-later                         https://www.gnu.org/software/inetutils
iputils-ping                distro   BSD-3-Clause AND GPL-2.0-or-later        https://github.com/iputils/iputils
jq                          distro   MIT                                      https://jqlang.github.io/jq
less                        distro   GPL-3.0-or-later OR BSD-2-Clause         https://www.greenwoodsoftware.com/less
libatomic1                  distro   GPL-3.0-or-later WITH GCC-exception-3.1  https://gcc.gnu.org
locales                     distro   LGPL-2.1-or-later                        https://www.gnu.org/software/libc
lsof                        distro   LicenseRef-lsof                          https://github.com/lsof-org/lsof
openssh-server              distro   SSH-OpenSSH                              https://www.openssh.com
postgresql-client-16        distro   PostgreSQL                               https://www.postgresql.org
python3, python-is-python3  distro   PSF-2.0                                  https://www.python.org
python3-dotenv              distro   BSD-3-Clause                             https://github.com/theskumar/python-dotenv
python3-pip                 distro   MIT                                      https://pip.pypa.io
python3-pytest              distro   MIT                                      https://pytest.org
rclone                      distro   MIT                                      https://rclone.org
redis-tools                 distro   BSD-3-Clause                             https://redis.io
ripgrep                     distro   MIT OR Unlicense                         https://github.com/BurntSushi/ripgrep
sudo                        distro   ISC                                      https://www.sudo.ws
supervisor                  distro   LicenseRef-supervisor                    http://supervisord.org
tini                        distro   MIT                                      https://github.com/krallin/tini
ubuntu:24.04 base image     24.04    LicenseRef-Debian-Copyright              https://ubuntu.com
vim                         distro   Vim                                      https://www.vim.org
zstd (build stage only)     distro   BSD-3-Clause OR GPL-2.0-only             https://github.com/facebook/zstd


9. CONTAINER IMAGE - DOWNLOADED BINARIES AND RUNTIMES
=====================================================

Downloaded by image/Dockerfile (and by start.sh/setup.sh in the dev VM).

NAME                      VERSION  LICENSE            HOMEPAGE
----                      -------  -------            --------
gh (GitHub CLI)           2.96.0   MIT                https://github.com/cli/cli
mcp-s3                    1.3.0    Apache-2.0         https://github.com/txn2/mcp-s3
Node.js (NodeSource)      24.x     MIT                https://nodejs.org
ollama                    0.32.14  MIT                https://github.com/ollama/ollama
ops (OpenServerless CLI)  latest   Apache-2.0         https://github.com/apache/openserverless-cli
uv (/usr/bin/uv)          latest   Apache-2.0 OR MIT  https://github.com/astral-sh/uv


10. OPS PREREQUISITES (oplugins/prereq.yml)
===========================================

Binaries `ops` downloads into ~/.ops/<os>-<arch>/bin on first run, in the
image and on every developer machine.

NAME                VERSION  LICENSE                                                  HOMEPAGE
----                -------  -------                                                  --------
7zz (7-Zip)         2407     LGPL-2.1-or-later AND BSD-3-Clause AND LicenseRef-unRAR  https://www.7-zip.org
bun                 1.3.14   MIT                                                      https://github.com/oven-sh/bun
coreutils (uutils)  0.0.27   MIT                                                      https://github.com/uutils/coreutils
helm                3.18.0   Apache-2.0                                               https://github.com/helm/helm
k3sup               0.13.13  MIT                                                      https://github.com/alexellis/k3sup
kind                0.30.0   Apache-2.0                                               https://github.com/kubernetes-sigs/kind
kubectl             1.33.1   Apache-2.0                                               https://github.com/kubernetes/kubernetes
rg (ripgrep)        14.1.0   MIT OR Unlicense                                         https://github.com/BurntSushi/ripgrep
uv                  0.7.19   Apache-2.0 OR MIT                                        https://github.com/astral-sh/uv
yq                  4.47.1   MIT                                                      https://github.com/mikefarah/yq
zip (Windows only)  3.0-1    Info-ZIP                                                 https://infozip.sourceforge.net


11. CONTAINER IMAGE - GLOBAL NPM INSTALLS
=========================================

Coding agents pinned in acp/pi.version plus the tools installed by
image/Dockerfile. Listed at top level; each package's own dependency
tree, with its license files, is installed under the global node_modules.

NAME                                    VERSION  LICENSE     HOMEPAGE
----                                    -------  -------     --------
@agentclientprotocol/codex-acp          1.1.4    Apache-2.0  https://www.npmjs.com/package/@agentclientprotocol/codex-acp
@earendil-works/pi-agent-core           0.82.0   MIT         https://github.com/earendil-works/pi
@earendil-works/pi-ai                   0.82.0   MIT         https://github.com/earendil-works/pi
@earendil-works/pi-coding-agent         0.82.0   MIT         https://github.com/earendil-works/pi
@earendil-works/pi-storage-sqlite-node  0.82.0   MIT         https://github.com/earendil-works/pi
@earendil-works/pi-tui                  0.82.0   MIT         https://github.com/earendil-works/pi
@openai/codex                           0.144.6  Apache-2.0  https://github.com/openai/codex
mongodb-mcp-server                      1.9.0    Apache-2.0  https://github.com/mongodb-js/mongodb-mcp-server
pi-mcp-adapter                          2.11.0   MIT         https://www.npmjs.com/package/pi-mcp-adapter
pi-web-access                           0.13.0   MIT         https://www.npmjs.com/package/pi-web-access
tsx                                     latest   MIT         https://github.com/privatenumber/tsx
typescript                              latest   Apache-2.0  https://github.com/microsoft/TypeScript
typescript-language-server              latest   Apache-2.0  https://github.com/typescript-language-server/typescript-language-server


12. CONTAINER IMAGE - PYTHON TOOLS (uv tool install)
====================================================

Each tool runs in its own uv-managed virtualenv under /opt/uv/tools.

NAME                               VERSION  LICENSE     HOMEPAGE
----                               -------  -------     --------
mcp (Python MCP SDK, <2)           1.x      MIT         https://github.com/modelcontextprotocol/python-sdk
mcp-server-milvus (fork, a7e624f)  a7e624f  Apache-2.0  https://github.com/trustable-ai/mcp-server-milvus
milvus-cli                         1.2.1    Apache-2.0  https://github.com/zilliztech/milvus_cli
postgres-mcp                       0.3.0    MIT         https://github.com/crystaldba/postgres-mcp
python-lsp-server                  latest   MIT         https://github.com/python-lsp/python-lsp-server
redis-mcp-server                   0.5.0    MIT         https://github.com/redis/mcp-redis
yapf                               latest   Apache-2.0  https://github.com/google/yapf


13. PYTHON PACKAGES FOR USER APPS (acp/extensions/requirements.txt)
===================================================================

Installed unmodified for the apps users build.

NAME                  VERSION      LICENSE                                             HOMEPAGE
----                  -------      -------                                             --------
annotated-types       0.8.0        MIT                                                 https://pypi.org/project/annotated-types
anyio                 4.15.1       MIT                                                 https://pypi.org/project/anyio
argon2-cffi           25.1.0       MIT                                                 https://pypi.org/project/argon2-cffi
argon2-cffi-bindings  26.1.0       MIT                                                 https://pypi.org/project/argon2-cffi-bindings
asn1crypto            1.5.1        MIT                                                 https://pypi.org/project/asn1crypto
bcrypt                5.0.0        Apache-2.0                                          https://pypi.org/project/bcrypt
beautifulsoup4        4.15.0       MIT                                                 https://pypi.org/project/beautifulsoup4
boto3                 1.43.97      Apache-2.0                                          https://pypi.org/project/boto3
botocore              1.43.97      Apache-2.0                                          https://pypi.org/project/botocore
cachetools            7.2.0        MIT                                                 https://pypi.org/project/cachetools
certifi               2026.7.22    MPL-2.0                                             https://pypi.org/project/certifi
cffi                  2.1.1        MIT-0                                               https://pypi.org/project/cffi
charset-normalizer    3.5.1        MIT                                                 https://pypi.org/project/charset-normalizer
click                 8.5.0        BSD-3-Clause                                        https://pypi.org/project/click
cloudpickle           3.1.2        BSD-3-Clause                                        https://pypi.org/project/cloudpickle
defusedxml            0.7.1        PSF-2.0                                             https://pypi.org/project/defusedxml
distro                1.9.0        Apache-2.0                                          https://pypi.org/project/distro
dnspython             2.8.0        ISC                                                 https://pypi.org/project/dnspython
feedparser            6.0.14       BSD-2-Clause                                        https://pypi.org/project/feedparser
feedparser-sgmllib    2.1.0        PSF-2.0                                             https://pypi.org/project/feedparser-sgmllib
grpcio                1.84.0       Apache-2.0                                          https://pypi.org/project/grpcio
h11                   0.16.0       MIT                                                 https://pypi.org/project/h11
httpcore              1.0.9        BSD-3-Clause                                        https://pypi.org/project/httpcore
httpcore2             2.13.0       BSD-3-Clause                                        https://pypi.org/project/httpcore2
httplib2              0.32.0       MIT                                                 https://pypi.org/project/httplib2
httpx                 0.28.1       BSD-3-Clause                                        https://pypi.org/project/httpx
httpx2                2.13.0       BSD-3-Clause                                        https://pypi.org/project/httpx2
idna                  3.20         BSD-3-Clause                                        https://pypi.org/project/idna
jiter                 0.17.0       MIT                                                 https://pypi.org/project/jiter
jmespath              1.1.0        MIT                                                 https://pypi.org/project/jmespath
joblib                1.6.0        BSD-3-Clause                                        https://pypi.org/project/joblib
jsonpatch             1.33         BSD-3-Clause                                        https://pypi.org/project/jsonpatch
jsonpointer           3.1.1        BSD-3-Clause                                        https://pypi.org/project/jsonpointer
kafka-python          3.0.11       Apache-2.0                                          https://pypi.org/project/kafka-python
langchain             1.4.1        MIT                                                 https://pypi.org/project/langchain
langchain-core        1.6.3        MIT                                                 https://pypi.org/project/langchain-core
langchain-protocol    0.0.19       MIT                                                 https://pypi.org/project/langchain-protocol
langdetect            1.0.9        Apache-2.0                                          https://pypi.org/project/langdetect
langgraph             1.2.11       MIT                                                 https://pypi.org/project/langgraph
langgraph-checkpoint  4.2.0        MIT                                                 https://pypi.org/project/langgraph-checkpoint
langgraph-prebuilt    1.1.0        MIT                                                 https://pypi.org/project/langgraph-prebuilt
langgraph-sdk         0.4.4        MIT                                                 https://pypi.org/project/langgraph-sdk
langsmith             0.12.6       MIT                                                 https://pypi.org/project/langsmith
minio                 7.2.20       Apache-2.0                                          https://pypi.org/project/minio
narwhals              2.26.0       MIT                                                 https://pypi.org/project/narwhals
nltk                  3.10.3       Apache-2.0                                          https://pypi.org/project/nltk
numpy                 2.5.3        BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0  https://pypi.org/project/numpy
ollama                0.6.2        MIT                                                 https://pypi.org/project/ollama
openai                3.15.0       Apache-2.0                                          https://pypi.org/project/openai
orjson                3.12.0       MPL-2.0 AND (Apache-2.0 OR MIT)                     https://pypi.org/project/orjson
ormsgpack             1.12.2       Apache-2.0 OR MIT                                   https://pypi.org/project/ormsgpack
packaging             26.3         Apache-2.0 OR BSD-2-Clause                          https://pypi.org/project/packaging
pandas                3.0.6        BSD-3-Clause                                        https://pypi.org/project/pandas
pg8000                1.31.5       BSD-3-Clause                                        https://pypi.org/project/pg8000
plotly                7.1.0        MIT                                                 https://pypi.org/project/plotly
protobuf              7.36.2       BSD-3-Clause                                        https://pypi.org/project/protobuf
psycopg               3.3.5        LGPL-3.0-only                                       https://pypi.org/project/psycopg
psycopg-binary        3.3.5        LGPL-3.0-only                                       https://pypi.org/project/psycopg-binary
pycparser             3.0          BSD-3-Clause                                        https://pypi.org/project/pycparser
pycryptodome          3.23.0       BSD-2-Clause AND LicenseRef-Public-Domain           https://pypi.org/project/pycryptodome
pydantic              2.13.5       MIT                                                 https://pypi.org/project/pydantic
pydantic-core         2.46.5       MIT                                                 https://pypi.org/project/pydantic-core
pymilvus              3.0.2        Apache-2.0                                          https://pypi.org/project/pymilvus
pymongo               4.18.1       Apache-2.0                                          https://pypi.org/project/pymongo
pyparsing             3.3.2        MIT                                                 https://pypi.org/project/pyparsing
python-dateutil       2.9.0.post0  Apache-2.0 AND BSD-3-Clause                         https://pypi.org/project/python-dateutil
python-dotenv         1.2.3        BSD-3-Clause                                        https://pypi.org/project/python-dotenv
pyyaml                6.0.3        MIT                                                 https://pypi.org/project/pyyaml
redis                 8.1.0        MIT                                                 https://pypi.org/project/redis
regex                 2026.9.10    Apache-2.0 AND CNRI-Python                          https://pypi.org/project/regex
requests              2.34.2       Apache-2.0                                          https://pypi.org/project/requests
requests-toolbelt     1.0.0        Apache-2.0                                          https://pypi.org/project/requests-toolbelt
s3transfer            0.19.2       Apache-2.0                                          https://pypi.org/project/s3transfer
scramp                1.4.17       MIT-0                                               https://pypi.org/project/scramp
six                   1.17.0       MIT                                                 https://pypi.org/project/six
sniffio               1.3.1        MIT OR Apache-2.0                                   https://pypi.org/project/sniffio
soupsieve             2.9.2        MIT                                                 https://pypi.org/project/soupsieve
tenacity              9.1.4        Apache-2.0                                          https://pypi.org/project/tenacity
tqdm                  4.70.1       MPL-2.0 AND MIT                                     https://pypi.org/project/tqdm
truststore            0.10.4       MIT                                                 https://pypi.org/project/truststore
typing-extensions     4.16.0       PSF-2.0                                             https://pypi.org/project/typing-extensions
typing-inspection     0.4.4        MIT                                                 https://pypi.org/project/typing-inspection
urllib3               2.8.0        MIT                                                 https://pypi.org/project/urllib3
uuid-utils            0.17.1       BSD-3-Clause                                        https://pypi.org/project/uuid-utils
websockets            16.1.1       BSD-3-Clause                                        https://pypi.org/project/websockets
xxhash                4.0.1        BSD-2-Clause                                        https://pypi.org/project/xxhash
zstandard             0.25.0       BSD-3-Clause                                        https://pypi.org/project/zstandard


14. DEVELOPMENT ENVIRONMENT ONLY (NOT DISTRIBUTED)
==================================================

Installed by start.sh / start.ps1 / setup.sh / run.sh on a developer
machine or dev VM. Not part of the binary or the image; no notices are
collected for them.

NAME                                  VERSION  LICENSE                                 HOMEPAGE
----                                  -------  -------                                 --------
@playwright/test (e2e tests)          1.56.1   Apache-2.0                              https://github.com/microsoft/playwright
air                                   latest   GPL-3.0-only                            https://github.com/air-verse/air
ffmpeg (screenshot.sh)                distro   LGPL-2.1-or-later AND GPL-2.0-or-later  https://ffmpeg.org
g (Go version manager)                latest   MIT                                     https://github.com/voidint/g
k3s                                   via ops  Apache-2.0                              https://github.com/k3s-io/k3s
kubefwd                               1.25.16  Apache-2.0                              https://github.com/txn2/kubefwd
license-eye (skywalking-eyes)         0.8.0    Apache-2.0                              https://github.com/apache/skywalking-eyes
Lima                                  latest   Apache-2.0                              https://github.com/lima-vm/lima
WSL2 / Ubuntu-24.04 distro (Windows)  -        LicenseRef-Debian-Copyright             https://ubuntu.com


LICENSE NOTES

- Claude Code (@anthropic-ai/claude-code) is proprietary. It is NOT included
  in Trustant, its image or this inventory: TruACP installs it on demand into
  the user's workspace only after the user accepts Anthropic's Commercial
  Terms (https://www.anthropic.com/legal/commercial-terms).
- psycopg / psycopg-binary are LGPL-3.0-only; they are installed as unmodified
  Python packages and dynamically imported, as the LGPL permits. Source:
  https://github.com/psycopg/psycopg
- 7-Zip (7zz) is LGPL-2.1-or-later with BSD-3-Clause parts and the unRAR
  restriction; it is the unmodified upstream binary. Source:
  https://www.7-zip.org
- MPL-2.0 components (certifi, ca-certificates, orjson, tqdm) are file-level
  copyleft and are shipped unmodified; sources are at their homepages.
- GPL/LGPL Ubuntu packages are the unmodified distribution binaries; their
  sources are available from the Ubuntu archive (apt-get source <package>).
- air is GPL-3.0 but is a development-only file watcher; it is never
  distributed with Trustant.
