// Copyright 2025-2026 Nuvolaris Inc
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package main

import (
	_ "embed"
	"net/http"
	"strings"
)

// The legal texts are generated by deps.sh and embedded so every binary carries
// the exact inventory, license texts and notices it was built with (see
// spec/20-legal.md). WHY embedded and not read from disk: the binary is
// distributed on its own, and the AGPL/Apache/MIT terms travel with it.

//go:embed DEPS
var legalDeps string

//go:embed NOTICE
var legalNotice string

//go:embed LICENSE
var legalLicense string

var legalTexts = map[string]*string{
	"deps":    &legalDeps,
	"notice":  &legalNotice,
	"license": &legalLicense,
}

// handleLegal serves GET /api/legal/{deps,notice,license} as plain text.
func handleLegal(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	text, ok := legalTexts[strings.TrimPrefix(r.URL.Path, "/api/legal/")]
	if !ok {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write([]byte(*text))
}
